config:
  AttriuteList:

    Attack_Speed_Name: "공격속도"

    Additioanl_Health_Name: "생명력"

    Absorption_Health_Name: "생명력흡수"

    Regeneration_Health_Name: "생명력재생"

    Defence_Damage_Name: "피해감소"

    Reduce_Damage_Name: "피해무시"

    Base_Attack_Damage_Name: "공격력"

    Normal_Attack_Damage_Name: "일반공격력"

    Skill_Attack_Damage_Name: "스킬공격력"

    Critical_Attack_Damage_Name: "치명타피해"

    Critical_Probability_Name: "치명타확률"

    Walk_Speed_Name: "이동속도"
  
  #로어의 어떤줄이 스탯을 담당하는지 구분하는 표식으로써 무엇을 사용할지 지정해 주세요.
  Lore_Identifier: "*"

  #최종 스킬 공격력에 관련된 이름을 적어주세요. 손에 든 아이템에 이 스탯이 있어야 스탯 값 덮어쓰기가 작동합니다.
  Total_Skill_Damage_Name: "최종 스킬 공격력"

  # 아래 값은 %로 처리 됩니다. 기본값: 100%, 단 %는 빼고 표기해 주세요
  Default_Walk_Speed: 150

  # 아래 값은 %로 처리 됩니다. 기본값: 50%, 단 %는 빼고 표기해 주세요
  Default_Critical_Damage: 50

  #기본 생명력 값입니다. 로그인 및 각 계산시에 기준으로 사용됩니다.
  Default_Health_Point: 10
  
  
